const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const machines=[['Washing Machine 1','Block A','AVAILABLE'],['Washing Machine 2','Block A','AVAILABLE'],['Washing Machine 3','Block A','IN_USE'],['Washing Machine 4','Block B','AVAILABLE'],['Washing Machine 5','Block B','MAINTENANCE'],['Washing Machine 6','Block B','AVAILABLE']].map((m,i)=>({id:i+1,name:m[0],block:m[1],status:m[2]}));
let selected=null,bookings=JSON.parse(localStorage.getItem('laundry-demo-bookings')||'[]'),reports=JSON.parse(localStorage.getItem('laundry-demo-reports')||'[]');
const auth=$('#auth'),video=document.createElement('video'),photo=document.createElement('img');video.className='auth-video';video.autoplay=true;video.muted=true;video.loop=true;video.playsInline=true;video.src='src/main/resources/web/background.mp4';photo.className='brand-photo';photo.src='src/main/resources/web/login-poster.png';photo.alt='Hostel Laundry illustration';auth.prepend(video);$('.brand-panel').append(photo);
function save(){localStorage.setItem('laundry-demo-bookings',JSON.stringify(bookings));localStorage.setItem('laundry-demo-reports',JSON.stringify(reports))}function note(t,e=false){const n=$('#notice');n.textContent=t;n.className='notice'+(e?' error':'');setTimeout(()=>n.textContent='',3500)}
function card(m){return `<article class="machine-card ${m.status==='AVAILABLE'?'available':''}" data-id="${m.id}"><strong>${m.name}</strong><small>${m.block}</small><span class="${m.status}">● ${m.status.replace('_',' ')}</span></article>`}
function renderMachines(){const h=machines.map(card).join('');$('#machine-preview').innerHTML=h;$('#book-machines').innerHTML=h;$('#report-machine').innerHTML=machines.map(m=>`<option value="${m.id}">${m.name} · ${m.block}</option>`).join('');$$('.machine-card.available').forEach(x=>x.onclick=()=>{selected=+x.dataset.id;$$('.machine-card').forEach(y=>y.classList.toggle('selected',+y.dataset.id===selected))})}
function render(){renderMachines();$('#stats').innerHTML=[['Total machines',machines.length],['Available now',machines.filter(m=>m.status==='AVAILABLE').length],['My bookings',bookings.length],['My reports',reports.length]].map(x=>`<article class="stat"><p>${x[0]}</p><b>${x[1]}</b></article>`).join('');$('#bookings-table').innerHTML=bookings.map(b=>`<tr><td>${b.date}</td><td>${b.time}–${String(+b.time.slice(0,2)+1).padStart(2,'0')}:00</td><td>${b.machine}</td><td><span class="badge">PENDING</span></td></tr>`).join('')||'<tr><td colspan="4">No demo bookings yet.</td></tr>';$('#reports').innerHTML=reports.map(r=>`<article class="panel"><b>${r.machine}</b><p>${r.text}</p><span class="badge">PENDING</span></article>`).join('')}
function show(p){$$('.page').forEach(x=>x.hidden=x.id!==p);$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#page-title').textContent={dashboard:'Dashboard',book:'Book Machine',bookings:'My Bookings',report:'Report Issue'}[p];render()}$$('[data-page]').forEach(x=>x.onclick=()=>show(x.dataset.page));$$('.go-book').forEach(x=>x.onclick=()=>show('book'));
$('#demo-login').onsubmit=e=>{e.preventDefault();const n=new FormData(e.target).get('name').trim();localStorage.setItem('laundry-demo-name',n);$('#user-name').textContent=n;$('#welcome-name').textContent=n;$('.avatar').textContent=n[0].toUpperCase();auth.hidden=true;$('#app').hidden=false;show('dashboard')};
$('#booking-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target),m=machines.find(x=>x.id===selected);if(!m)return note('Choose an available machine first.',true);bookings.push({date:d.get('date'),time:d.get('start'),machine:m.name});save();e.target.reset();selected=null;note('Demo booking confirmed.');show('bookings')};
$('#report-form').onsubmit=e=>{e.preventDefault();const text=$('#report-text').value.trim();if(!text)return note('Please describe the issue.',true);reports.push({machine:machines.find(x=>x.id===+$('#report-machine').value).name,text});save();e.target.reset();note('Demo issue report submitted.');render()};
const theme=document.createElement('button');theme.className='theme-toggle';$('.user').prepend(theme);function setTheme(v){document.body.classList.toggle('dark',v==='dark');theme.textContent=v==='dark'?'Light mode':'Dark mode'}setTheme(localStorage.getItem('laundry-demo-theme')||'light');theme.onclick=()=>{const n=document.body.classList.contains('dark')?'light':'dark';localStorage.setItem('laundry-demo-theme',n);setTheme(n)};$('#logout').onclick=()=>{auth.hidden=false;$('#app').hidden=true};const n=localStorage.getItem('laundry-demo-name');if(n){$('#demo-login [name=name]').value=n}
